FROM node:latest

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install -g ts-node
RUN npm install -g nodemon

COPY . .

RUN npm run build

EXPOSE 3000

ENTRYPOINT ["npm", "run", "dev"]
